### ISSUE TITLE
Keep the protein file

### ISSUE THREAD

**Issue by elizabethmcd** [ctSkennerton/kegg_hmm_models#2]
Great tool! This has saved me a lot of time building a couple HMM profiles.
I would like to make a suggestion to keep the protein fasta file for then testing the HMM profile against those sequences to figure out a cutoff range for use with other sequences. For now I've just copied the protein file to another location while the Makefile is running.

**Comment by ctSkennerton** [comment]
You can set this globally in the Makefile. you can add faa files to the list of precious files:

```
#from 
.PRECIOUS: %.hmm
# to
.PRECIOUS: %.hmm %.faa
```

**Comment by elizabethmcd** [comment]
Ah thanks!
